// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/ReusableComponents/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./src/components/ReusableComponents/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./src/components/ReusableComponents/BaseInput.vue')['default']
    BaseInputTel: typeof import('./src/components/ReusableComponents/BaseInputTel.vue')['default']
    BaseRadio: typeof import('./src/components/ReusableComponents/BaseRadio.vue')['default']
    BaseRadioGroup: typeof import('./src/components/ReusableComponents/BaseRadioGroup.vue')['default']
    BaseSelect: typeof import('./src/components/ReusableComponents/BaseSelect.vue')['default']
    ChartComponents: typeof import('./src/components/charts/ChartComponents.vue')['default']
    ModalConfirmRegister: typeof import('./src/components/modal/ModalConfirmRegister.vue')['default']
    ModalRestorePassword: typeof import('./src/components/modal/ModalRestorePassword.vue')['default']
    MySpinner: typeof import('./src/components/Utilities/MySpinner.vue')['default']
    PanelHeader: typeof import('./src/components/panel/PanelHeader.vue')['default']
    PanelLoginUser: typeof import('./src/components/panel/PanelLoginUser.vue')['default']
    PanelUserProfile: typeof import('./src/components/panel/PanelUserProfile.vue')['default']
    RegisterLogin: typeof import('./src/components/register/RegisterLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
