// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/ReusableComponents/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./src/components/ReusableComponents/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./src/components/ReusableComponents/BaseInput.vue')['default']
    BaseInputTel: typeof import('./src/components/ReusableComponents/BaseInputTel.vue')['default']
    BaseRadio: typeof import('./src/components/ReusableComponents/BaseRadio.vue')['default']
    BaseRadioGroup: typeof import('./src/components/ReusableComponents/BaseRadioGroup.vue')['default']
    BaseSelect: typeof import('./src/components/ReusableComponents/BaseSelect.vue')['default']
    BaseSelectFlags: typeof import('./src/components/ReusableComponents/BaseSelectFlags.vue')['default']
    BubbleInfo: typeof import('./src/components/modal/BubbleInfo.vue')['default']
    Carousel: typeof import('./src/components/modal/Carousel.vue')['default']
    ChartComponents: typeof import('./src/components/charts/ChartComponents.vue')['default']
    GridHallazgo: typeof import('./src/components/modal/GridHallazgo.vue')['default']
    MapaGeneral: typeof import('./src/components/MapaGeneral.vue')['default']
    ModalConfirmRegister: typeof import('./src/components/modal/ModalConfirmRegister.vue')['default']
    ModalHistorico: typeof import('./src/components/modal/ModalHistorico.vue')['default']
    ModalImagenes: typeof import('./src/components/modal/ModalImagenes.vue')['default']
    ModalMessages: typeof import('./src/components/modal/ModalMessages.vue')['default']
    MySpinner: typeof import('./src/components/Utilities/MySpinner.vue')['default']
    PanelAgreement: typeof import('./src/components/panel/PanelAgreement.vue')['default']
    PanelConvenciones: typeof import('./src/components/panel/PanelConvenciones.vue')['default']
    PanelDashboard: typeof import('./src/components/panel/PanelDashboard.vue')['default']
    PanelFilters: typeof import('./src/components/panel/PanelFilters.vue')['default']
    PanelFiltros: typeof import('./src/components/panel/PanelFiltros.vue')['default']
    PanelHeader: typeof import('./src/components/panel/PanelHeader.vue')['default']
    PanelImportCSV: typeof import('./src/components/panel/PanelImportCSV.vue')['default']
    PanelLateral: typeof import('./src/components/panel/PanelLateral.vue')['default']
    PanelLogin: typeof import('./src/components/login/PanelLogin.vue')['default']
    PanelLoginUser: typeof import('./src/components/panel/PanelLoginUser.vue')['default']
    PanelUserProfile: typeof import('./src/components/panel/PanelUserProfile.vue')['default']
    PanelUsuario: typeof import('./src/components/panel/PanelUsuario.vue')['default']
    RegisterLogin: typeof import('./src/components/register/RegisterLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
